"""Grocery category detection from ingredient names.

Maps ingredient names to grocery store categories using keyword matching.
"""

from api.models.grocery_list import GroceryCategory

CATEGORY_KEYWORDS: dict[GroceryCategory, set[str]] = {
    GroceryCategory.PRODUCE: {
        "apple",
        "apples",
        "avocado",
        "banana",
        "basil",
        "bean",
        "beans",
        "bell pepper",
        "broccoli",
        "cabbage",
        "carrot",
        "carrots",
        "celery",
        "chili",
        "chive",
        "chives",
        "cilantro",
        "corn",
        "cucumber",
        "dill",
        "eggplant",
        "fruit",
        "garlic",
        "ginger",
        "grape",
        "grapes",
        "green",
        "greens",
        "herb",
        "herbs",
        "kale",
        "leek",
        "lemon",
        "lettuce",
        "lime",
        "mango",
        "mint",
        "mushroom",
        "mushrooms",
        "onion",
        "onions",
        "orange",
        "oregano",
        "parsley",
        "pea",
        "peas",
        "pepper",
        "peppers",
        "potato",
        "potatoes",
        "rosemary",
        "sage",
        "salad",
        "scallion",
        "scallions",
        "shallot",
        "shallots",
        "spinach",
        "squash",
        "strawberry",
        "thyme",
        "tomato",
        "tomatoes",
        "vegetable",
        "vegetables",
        "zucchini",
    },
    GroceryCategory.MEAT_SEAFOOD: {
        "anchovy",
        "bacon",
        "beef",
        "chicken",
        "clam",
        "cod",
        "crab",
        "duck",
        "fish",
        "ground beef",
        "ground pork",
        "ham",
        "lamb",
        "lobster",
        "meat",
        "meatball",
        "mussel",
        "oyster",
        "pork",
        "prawn",
        "salmon",
        "sausage",
        "scallop",
        "seafood",
        "shrimp",
        "steak",
        "tuna",
        "turkey",
        "veal",
    },
    GroceryCategory.DAIRY: {
        "butter",
        "cheddar",
        "cheese",
        "cream",
        "cream cheese",
        "crème fraîche",
        "egg",
        "eggs",
        "feta",
        "goat cheese",
        "greek yogurt",
        "half and half",
        "heavy cream",
        "milk",
        "mozzarella",
        "parmesan",
        "ricotta",
        "sour cream",
        "whipping cream",
        "yogurt",
    },
    GroceryCategory.BAKERY: {
        "bagel",
        "baguette",
        "bread",
        "brioche",
        "bun",
        "ciabatta",
        "cracker",
        "croissant",
        "flatbread",
        "muffin",
        "naan",
        "pita",
        "roll",
        "sourdough",
        "tortilla",
    },
    GroceryCategory.PANTRY: {
        "baking powder",
        "baking soda",
        "bay leaf",
        "bouillon",
        "broth",
        "canned",
        "capers",
        "cayenne",
        "chili flakes",
        "cinnamon",
        "cocoa",
        "coconut milk",
        "cornstarch",
        "cumin",
        "curry",
        "dried",
        "flour",
        "honey",
        "ketchup",
        "maple syrup",
        "mayonnaise",
        "mustard",
        "noodle",
        "noodles",
        "nut",
        "nuts",
        "oil",
        "olive oil",
        "paprika",
        "pasta",
        "peanut butter",
        "pepper",
        "rice",
        "salt",
        "sauce",
        "sesame",
        "soy sauce",
        "spice",
        "stock",
        "sugar",
        "syrup",
        "tahini",
        "vanilla",
        "vinegar",
        "worcestershire",
    },
    GroceryCategory.FROZEN: {"frozen", "ice cream", "popsicle", "sorbet"},
    GroceryCategory.BEVERAGES: {"beer", "coffee", "juice", "soda", "tea", "water", "wine"},
}


def detect_category(ingredient_name: str) -> GroceryCategory:
    """Detect the grocery store category for an ingredient.

    Args:
        ingredient_name: The ingredient name to categorize.

    Returns:
        The matching GroceryCategory, or OTHER if no match found.
    """
    name_lower = ingredient_name.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        for keyword in keywords:
            if keyword in name_lower:
                return category
    return GroceryCategory.OTHER
